README.md
Add Text classfication, VDCN bechmarks
* Text classification
* AGnews: 8.67
* DBpedia: 1.29
* paper: https://arxiv.org/abs/1606.01781
* authors: Alexis Conneau, Holger Schwenk, Loïc Barrault, Yann Lecun
=> Add Text classification, VDCN benchmarks: AGnews, DBpedia

text_classification.md
The result:
| CNN (Johnson and Zhang, 2016) | 6.57 | [Supervised and Semi-Supervised Text Categorization using LSTM for Region Embeddings](https://arxiv.org/abs/1602.02373) |
does not appear in the mentioned paper.
=> Result not in the paper

language_modeling.md
Added SoTA results for char-level language modelling on Hutter Prize (enwik8), Text8 and Penn Treebank datasets. It's based mainly on [An Analysis of Neural Language Modeling at Multiple Scales](https://arxiv.org/abs/1803.08240) (Merity et al., 2018) and a few other sources for Text8.
=> Character Level Language Modeling Results

README.md
A link to an implementation is useful and should be added if it exists, as discussed in https://github.com/sebastianruder/NLP-progress/issues/16.
=> Added instructions to add source code to methods

summarization.md
Add results from a [new ACL 2018 paper](https://arxiv.org/abs/1805.11080).
Also add columns for a new evaluation (METEOR) and Code.
NOTE: The scores are reported in the paper's [official code repository](https://github.com/chenrocks/fast_abs_rl), where new high scores are achieved.
=> Add new paper for summarization

semantic_role_labeling.md
Added SOTA results for SRL with/without ELMO.
Publication Venues:
With ELMO: ACL 2018 (Jointly Predicting Predicates and Arguments in Neural Semantic Role Labeling)
Without ELMO: AAAI 2018 (Deep Semantic Role Labeling with Self-Attention)
=> New results: Semantic Role Labeling

.gitignore, _data/ccg_supertagging.yaml, _data/chunking.yaml, _data/constituency_parsing.yaml, _includes/chart.html, _includes/table.html, ccg_supertagging.md, chunking.md, constituency_parsing.md
Related to #43.
Right now did some demo for CCG. I didn't work on the plot form, just wanted to show it is possible and easy. Also - I think that data form can be standarized - so it would be simpler to add more complicated things (e.g. further comments, links to multiple implementations, etc).
See files in:
* `_data` - data in YAML format
* `_includes` - for ways of converting data into its presentations (tables, charts, etc)
* `ccg_supertagging.md` to see how to include these
IMHO YAML is cleaner for writing and reading than markdown tables, so it is an advantage on its own. From my experience contributors (ones who use GitHub) have no slightest problem in using YAML (vide https://p.migdal.pl/interactive-machine-learning-list/).
Right now I generate data through Liquid template.
* …
=> Data in YAML for structure and plots

README.md, relationship_extraction.md
I thought I'd add results on NYT, a standard dataset for distantly-supervised relationship extraction. It wasn't totally straightforward as there isn't a common metric used, most papers just publish precision/recall plots.
=> Add relationship extraction page with NYT task

text_classification.md
Better SOTA for TREC-6 is reported by "Universal Sentence Encoder" paper.
=> TREC-6 SOTA

english/summarization.md
Added results of most summarization models evaluated on CNN/DailyMail, Gigaword or DUC04 Task 1 published in between 2015 and 2018 in ACL/EMNLP/NAACL/EACL/COLING/ICLR/AAAI. EMNLP 2018 not yet included.
=> Added results of neural summarization models 2015-2018

english/summarization.md
Changed the name of the model in the paper "Entity Commonsense Representation for Neural Abstractive Summarization" from BASE+E2T_cnn+sd to Seq2seq + E2T_cnn.
=> Update model name from E2T paper

english/chunking.md, english/named_entity_recognition.md, english/part-of-speech_tagging.md
The results of NCRF++ (Yang and Zhang ACL 2018 ) on POS/Chunking/NER are updated. 
BTW, the result of  Liu, et al AAAI 2018 in NER is corrected from 91.71-> 91.24, as the author updated their result in GitHub.
=> add NCRF++ model results on POS/Chunking/NER

english/language_modeling.md
adding Character-Level Language Modeling with Deeper Self-Attention to language_modeling.md
even though it is not a published paper, I think it's good to have it to show that transformers can be used to obtain SotA on language modeling as well as being great pretrained models (like BERT)
=> add character transformer model to LM

english/question_answering.md
Update new results (NewsQA) for new model in NIPS 2018 (https://arxiv.org/abs/1811.04210)
Also add missing baseline (AMANDA) for NewsQA dataset.
=> Add new SOTA for NewsQA and missing baseline

english/question_answering.md
Quasar is a widely used open-domain question answering dataset, which has been used in [Wang et al., 2018] and [Lin et al. 2018].
=> Add a reading comprehension dataset Quasar

english/question_answering.md
I separate OpenQA dataset (DuReader, Quasar, SearchQA) from RC dataset. OpenQA is different from RC, which has multiple paragraphs for a question obtained by searching.
I also add Denoising QA and R^3 baselines for SearchQA dataset.
I also fix some writing issue in Quasar.
=> Separate OpenQA dataset from RC dataset

english/word_sense_disambiguation.md
Web links had extra parentheses that made the link not work.
=> Fix weblinks for English word sense disambiguation

english/named_entity_recognition.md
Add results for conll and ontonotes.
Mark paper that used both the train and development splits for training.
=> NER: Add results + mark comparable

english/semantic_parsing.md
- including the details about inputs (POS, NER, et al.) for each system
- making the rounding of numbers consistent across different tables
- add Liu et al. (2018) and Wang and Xue (2017) for LDC2014T12
=> A bunch of updates on the AMR parsing results

english/semantic_parsing.md
The leaderboard in the WikiSQL repo shows a bunch of newer implementations beating the ones shown here by a significant margin. Better to just link to the maintained WikiSQL leaderboard, like this page already does for the Spider dataset.
Alternatively, could update this table with those newer entries in the WikiSQL leaderboard. Note the current misalignment on TypeSQL: the WikiSQL leaderboard only lists the score for TypeSQL _without_ table content awareness (don't know why), while the leaderboard here only lists the score for TypeSQL _with_ table content awareness, hence the considerably higher score. Still, both are pretty far short of the current record holders in the WikiSQL leaderboard.
=> Point to Salesforce's leaderboard for WikiSQL

english/part-of-speech_tagging.md
Hi,
this PR corrects and adds new results for PoS tagging on Universal Dependencies. The result from the Yasunaga et al. paper was too high and even not consistent with their [reported result](https://arxiv.org/pdf/1711.04903.pdf) (see table 2).
Additionally, the result from Nguyen et al., 2017 is not directly comparable to the other papers, because some languages are missing. So only 17 languages can directly be compared.
Furthermore, this PR adds some new results from an upcoming ACL paper by @bheinzerling and Strube: [Sequence Tagging with Contextual and Non-Contextual Subword Representations: A Multilingual Evaluation](https://arxiv.org/abs/1906.01569).
Here's a table that allows a direct comparison of all 21 languages across all papers:
Language | Joint Bi-LSTM | Bi-LSTM | …
=> PoS tagging: correct and add new results

english/relationship_extraction.md
The paper was accepted at NAACL 2019. The P@10% and P@30% reported are based on the average scores over 5 runs according to the replication results in the code repo.
=> Add HRERE to task relation extraction on NYT corpus

english/text_classification.md
Noticed that there was no BERT result in text_classification.md - adding to show performance relative to ULMFiT and XLNET. This BERT result is not from the original BERT paper, but from https://arxiv.org/abs/1904.12848
=> BERT text classification result

english/summarization.md
add HIBERT (Zhang et al., 2019) and Two-Stage BERT (Zhang et al., 2019)
=> Update CNN/Daily Mail non-anonymized version

english/grammatical_error_correction.md
Partially addresses https://github.com/sebastianruder/NLP-progress/issues/318 . Will add more links to scores and code links as and when they are made available.
=> Include BEA Shared task on GEC

english/grammatical_error_correction.md
Following paper achieved the state-of-the-art performance on CoNLL2014 test set and BEA-2019 shared task (restricted track): [An Empirical Study of Incorporating Pseudo Data into Grammatical Error Correction](https://arxiv.org/abs/1909.00502).
The paper will appear in the proceedings of EMNLP-IJCNLP 2019.
=> Added new result for GEC

english/relationship_extraction.md
Add an extra line between "More examples:" and the markdown table to resolve markdown UI bug.
Preview of the before and after the change:
and thank you for maintaining this repository 👍
=> Fix Capturing discriminative attributes example table

english/named_entity_recognition.md
The results are not state-of-the-art, but they include a source code compared to the current SOTA model. Also they are SOTA for several nested NER datasets.
=> Add ACL 2019 Nested NER results for CoNLL 2003

english/language_modeling.md
Adds published results on 3 datasets from https://arxiv.org/abs/1909.08700
The code is hosted here: https://github.com/nkcr/overlap-ml
This paper proposes a new method for generating data-points out of datasets that are used for language modeling. It is interesting because it can be applied in all the current models since it only works at the dataset level. In the results, the best model of that time was used, which is AWD-LSTM-MoS.
=> Adds results for language modeling

english/grammatical_error_correction.md
This method may indeed combine models other than the one used, but is a GEC specific proposal (unlike average ensembling) and thus important to keeping track of state of the art.
=> Add the GEC specific combining

english/summarization.md
Results of BART added (CNN/DM abstractive).
Note : I put the result at the top of the CNN/DM list, even if the results of HierNSE are higher, because as mentioned in #369, these results does not belong in the same table.
=> Added BART (summarization)

english/summarization.md
Title speaks for itself I think. The table under "Non-Anonymized: Abstractive Models & Mixed Models" on the summarization page is currently not rendered because of newlines in the table definition.
=> remove newlines from BART addition in markdown file to fix table

english/named_entity_recognition.md
This paper achieved a 93.47 F1 score on the CoNLL 2003 English NER task. We improved LSTM-CRF+Flair by a searched RNN cell. The code and pre-trained model will be released after another paper is published.
=> Add a result for English NER

english/summarization.md
Results of UniLM added (CNN/DM abstractive & Gigaword).
Added results are the practical results, from the official code (theorical results, from the paper, are a bit higher).
Note : I put the result at the top of the CNN/DM list, even if the results of HierNSE are higher, because as mentioned in #369, these results does not belong in the same table.
=> Added UniLM (Summarization)

README.md, english/intent_detection_slot_filling.md, english/spoken_language_understanding.md
Added Spoke Language Understand for English as mentioned in #380 
Added two datasets (ATIS, SNIPS), notable results and repo (if available).
=> Added new task: Spoken Language Understanding

english/intent_detection_slot_filling.md
Changed BIO full form from "Inside Outside Between" to "Inside Outside Beginning".
=> Typo correction for BIO full form

english/part-of-speech_tagging.md
Add part-of-speech tagging result with EMNLP 2018 long paper (Learning Better Internal Structure of Words for Sequence Labeling), this paper proposed IntNet, which mainly focus on learning better character-to-word representations, IntNet significantly outperformed other character embedding models, and also combined with BiLSTM-CRF achieved state-of-the-art part-of-speech tagging result without using any lexical features, transfer learning, language modeling or pre-training.
=> Add part-of-speech tagging result

english/named_entity_recognition.md
Add NER state-of-the-art result with EMNLP 2018 paper (Learning Better Internal Structure of Words for Sequence Labeling), this paper proposed IntNet, which mainly focus on learning better character-to-word representations, IntNet significantly outperformed other character embedding models, and also combined with BiLSTM-CRF achieved state-of-the-art NER result without using any lexical features, transfer learning, language modeling or pre-training.
=> add NER state-of-the-art result

english/language_modeling.md
The results have not been peer reviewed and are too extreme to be considered believable. Dropping until accepted.
=> Drop TCAN from language-modelling leaderboards

english/entity_linking.md
AIDA A (development set) results were reported instead of AIDA B (test set). Fixed results taken from https://arxiv.org/pdf/1808.07699.pdf (Kolitsas, 2018) Table 2.
=> Report test set results instead of devel.

english/summarization.md
I added the results of our paper [1] to the table for the Google dataset in the sentence compression section.
[1]: Kamigaito et al., 2020, "Syntactically Look-A-Head Attention Network for Sentence Compression", https://arxiv.org/abs/2002.01145
=>  Update results for the Google dataset in sentence compression

english/grammatical_error_correction.md
Paper has been accepted at the 15th Workshop on Innovative Use of NLP for Building Educational Applications (co-located with ACL 2020). We set a new SOTA for the GEC task with up to 10x faster model than the previous SOTA. 
Paper: https://arxiv.org/pdf/2005.12592.pdf
Code: https://github.com/grammarly/gector
=> Add new SOTA results from GECToR

README.md, english/data_to_text_generation.md
I have added a new task of Data-to-Text Natural Language Generation (D2T NLG). 
D2T NLG differs from other NLG tasks such as MT or QA in a way that the input to text generation system is a structured representation (table, knowledge graph, or JSON) instead of unstructured text. 
This document provides an overview of three most recent and popular datasets available publicly for D2T NLG.
With the advancements in deep learning - several novel neural methods are being proposed that are capable of generating accurate, fluent and diverse texts.
=> Added new task: data-to-text generation

english/entity_linking.md
Hi, I have updated the table to include our latest paper (CIKM 2020) which is the current sota on ConLL-AIDA dataset. We will be releasing the code soon and will add the link in the future PRs.
=> Update entity_linking.md to include current sota on ConLL-AIDA dataset

english/coreference_resolution.md
Their paper "Revealing the Myth of Higher-Order Inference in Coreference Resolution" is accepted at emnlp.
=> Include results from recent Xu et al paper

english/semantic_parsing.md
LDC2016E25 is the release limited to DEFT participants in 2016. LDC2017T10 is the general public release of this data and the name used in all recent papers.  I believe the data is exactly the same (it definitely has the same number of train/test/dev samples).
=> Fix dataset title in semantic_parsing.md

english/entity_linking.md
Hi,
I have modified the end-to-end entity linking for CoNLL-AIDA dataset with a new paper to appear in EACL 2021.
=> New end-to-end entity linking SotA from EACL 2021

english/sentiment_analysis.md
In my original PR, I used "* et al.", but I just realized that I should use "and" as there are just two of us. Please help with merging this minor fix! Thanks!
=> fix author name for Wu & Ong 2020 SemEval paper

english/grammatical_error_correction.md
New SOTA on grammatical error correction obtained by training T5 on cLang-8, a relabeled version of the Lang-8 dataset. The paper (https://arxiv.org/pdf/2106.03830.pdf) has been accepted to ACL-IJNLP 2021.
=> New SOTA on GEC using T5 (ACL-IJCNLP 2021)

english/entity_linking.md
- CHOLAN score is Micro-F1-strong not Macro-F1-strong
- Sorted the systems based on Micro-F1-strong, similar to Disambiguation-only models
=> Updated EL End-to-End Models

english/relationship_extraction.md
Hi,
Please consider the pull request for the updated SOTA table for NYT freebase and Wikidata for relation extraction.
To apper in ACL 2021
Abhishek
=> Updated SOTA NYT freebase and WikiData for RE (ACL 2021)

english/ccg.md
- Clarified evaluation procedures and metrics for parsing and supertagging
- Explained constructive supertagging
- Added recent constructive supertagging results from Bhargava & Penn (2020) and Prange et al. (2021)
- Added new results tables for supertagging on Wikipedia domain and retrieving rare supertags
I'm not sure how appropriate it is to report 2 different results from our own paper (constructive and non-constructive), so let me know if I should remove one of them, but I think it is more transparent this way, especially as more people are starting to work on constructive tagging.
=> Updated CCG progress

vietnamese/vietnamese.md
- NER: PhoNER_COVID19 is a new NER dataset for Vietnamese. The dataset and results are reported in [COVID-19 Named Entity Recognition for Vietnamese (NAACL 2021)](https://www.aclweb.org/anthology/2021.naacl-main.173/)
- Intent Detection and Slot Filling: PhoATIS is a new Intent Detection and Slot Filling dataset for Vietnamese. The dataset, model, and results are reported in [Intent Detection and Slot Filling for Vietnamese (INTERSPEECH 2021)](https://arxiv.org/abs/2104.02021)
=> add NER Vietnamese result for PhoNER_COVID19, add Intent Detection and Slot Filling result for PhoATIS

vietnamese/vietnamese.md
PhoNLP obtained a new SOTA result for Vietnamese Dependency parsing, and new results for NER and POS Tagging. The paper [https://aclanthology.org/2021.naacl-demos.1.pdf](url) has been accepted at NAACL 2021.
=> Add SOTA result for Vietnamese Dependency parsing, and new results for NER and POS Tagging

README.md, vietnamese/vietnamese.md
Adding a new section for intent detection/slotfilling in `README.md` as I forgot to do so in the previous pull request.
Rearrange tasks in `vietnamese/vietnamese.md` into alphabetical order.
Sorry for the inconvenience caused.
=> Add Vietnamese intent detection and slot filling into task list

README.md, vietnamese/vietnamese.md
Add a new task and results for the Text-to-SQL Semantic Parsing problem to Vietnamese on the gold corpus ViText2SQL published at EMNLP Findings 2020.
[A Pilot Study of Text-to-SQL Semantic Parsing for Vietnamese](https://aclanthology.org/2020.findings-emnlp.364/)
=> Add Vietnamese SQL semantic parsing

english/semantic_parsing.md
Markdown table wasn't parsed correctly by github pages (but weirdly it was by the github preview and https://dillinger.io/). I guess it was because of a missing newline. Now everything should be fine.
Also, the "number of sentences" lines are now uniform.
=> fix Markdown error

french/summarization.md
In this pull request we propose adding [OrangeSum](https://huggingface.co/datasets/orange_sum) french abstractive summarization dataset introduced in [BARThez: a Skilled Pretrained French Sequence-to-Sequence Model](https://aclanthology.org/2021.emnlp-main.740/).
=> Add OrangeSum

vietnamese/vietnamese.md
Add [PhoMT dataset and results](https://aclanthology.org/2021.emnlp-main.369/) for English-Vietnamese Machine Translation.
=> Add new dataset and results for English-Vietnamese Machine Translation

english/part-of-speech_tagging.md
Added the UD POS tagging results from Substructure Substitution: Structured Data Augmentation for NLP (Shi et al., Findings of ACL 2021).
=> Add UD POS tagging Results

english/semantic_role_labeling.md
Add new results and a new dataset for SRL.
=> Add new results and a new dataset for SRL

russian/sentiment-analysis.md
https://arxiv.org/pdf/2305.17679.pdf
RuSentNE-2023: Evaluating Entity-Oriented Sentiment Analysis on Russian News Texts.
The paper describes the RuSentNE-2023 evaluation devoted to targeted sentiment analysis in Russian news
texts. The task is to predict sentiment towards a named entity in a single sentence. The dataset for RuSentNE-2023
evaluation is based on the Russian news corpus RuSentNE having rich sentiment-related annotation. The corpus
is annotated with named entities and sentiments towards these entities, along with related effects and emotional
states. The evaluation was organized using the CodaLab competition framework. The main evaluation measure
was macro-averaged measure of positive and negative classes. The best results achieved were of 66% Macro Fmeasure …
=> Added RuSentNE-2023 evaluation
