README.md

Added multimodal datasets and SOTA models.

Added Multimodal papers

---

text_classification.md

Subtracted a few numbers, to report Error as indicated (and not accuracy)

Tex classification: changed accuracy to error

---

part-of-speech_tagging.md

Updated part of speech tagging

---

README.md

This paper lists papers on the topic along with stats, if anyone's interested:
http://www.hlt.utdallas.edu/~vince/papers/acl14-keyphrase.pdf

Add keyphrase extraction

---

README.md
entity_linking.md

As asked in #17, here the ```entity_linking.md``` file.

Add Entity Linking task

---

README.md

I propose this change to cover grammatical acceptability, as in https://arxiv.org/abs/1805.12471 (which contains both methods and dataset).
Possibly related to this field, see also https://link.springer.com/chapter/10.1007/978-3-319-10888-9_47 for a dataset.
I am not an NLP expert so I am not yet confident in contributing but can open an issue if useful!
Sorry if this is included already in other categories, feel free to reject if that's the case:)

Add grammatical acceptability to wishlist

---

semantic_parsing.md

Added a range of datasets, results, examples, and links to code.

Adding more text-to-SQL datasets

---

text_classification.md

I was looking for `ULMFiT` implementation, and I thought it would be a nice excuse to start adding links to code to this repo.
Let me know what you think, maybe you'd prefer a single, large PR, but I don't have bandwidth to look for all the implementations at the moment :(

Add ref to ULMFiT code

---

multimodal.md

Added a section for some of the research on Multimodal (specifically visual and text) Metaphor Recognition.

Added a section for Multimodal Metaphor Recognition

---

question_answering.md

Added new results on Story Cloze Test

---

named_entity_recognition.md

COLING 2018 paper on embeddings produced by pre-trained character-level language models. Code available as framework for reproduction of experiments.

Added results of recent paper / code

---

README.md
named_entity_recognition.md
part-of-speech_tagging.md
stance.md
time.md
timexnorm.md

New tasks (temporal, stance) and new datasets (soc med in NER, POS)

---

semantic_textual_similarity.md

Publication venue: International Conference on Learning Representations, 2018
There is also one more new result that is a slight improvement to this (here: https://arxiv.org/pdf/1805.11360.pdf ) not yet published though, I was able to only find it on arxiv.

new result: added Gong results to STS Quora table

---

semantic_textual_similarity.md

I added the implementation of 3 of the work in the STS Quora table by the authors

added code column for STS Quora table

---

dependency_parsing.md

Separate results from constituent parsers

Add dependency parsing results, clarify conversion tool v3.3.0

---

README.md
grammatical_error_correction.md

Add CONLL-14 and JFLEG datasets, and  their respective SOTA models.

Grammatical Error Correction

---

text_classification.md

Add official and non official code links for text classification

Add links to code

---

sentiment_analysis.md

Added SemEval to Sentiment Analysis

Added SemEval to Sentiment Analysis

---

named_entity_recognition.md
part-of-speech_tagging.md

Update the result list of CoNLL03 NER dataset and PTB POS tagging dataset.

add results of LM-LSTM-CRF (Liu et al., AAAI 18) 

---

_data/dependency_parsing.yaml
_data/dialog.yaml
_data/domain_adaptation.yaml
_data/entity_linking.yaml
_data/grammatical_error_correction.yaml
_data/language_modeling.yaml
_includes/chart.html
_includes/table.html
ccg_supertagging.md
chunking.md
constituency_parsing.md
dependency_parsing.md
dialog.md
domain_adaptation.md
entity_linking.md
grammatical_error_correction.md
language_modeling.md

Vide #64 .
Added: multiple scores for tables (with `dialog` as an example). 
Will add possibility for linking `code`.

More YAMLization

---

README.md

Text normalization is a problem of transforming text to its spoken form.
Example:
Source text: A baby giraffe is 6ft tall and weighs 150lb.
Normalized test: A baby giraffe is six feet tall and weighs one hundred fifty pounds.

Add text normalization to wishlist

---

README.md
_data/language_modeling.yaml
language_modeling.md

New state-of-the-art results on character-level language modeling using transformers.
Paper: [Character-Level Language Modeling with Deeper Self-Attention
](https://arxiv.org/abs/1808.04444)

Add T12 and T64 results for enwik8 and text8

---

sentiment_analysis.md

- Added some additional statistics on the IMDb dataset.
- Changed the label "score" to "accuracy" on the table, as it is more descriptive.

Add additional statistics on the IMDb dataset

---

README.md
_data/relation_prediction.yaml
relation_prediction.md

<s>I did not get `yaml` working on my local machine so I hope it builds from my careful (?) mimicry.</s>
It all works now. Ready to merge on my end :)

new task - relation prediction on WN18RR

---

entity_linking.md

contains details about xlingual EL approaches and numbers.

Added the AAAI18 xlingual EL paper

---

_data/entity_linking_disambiguation_only.yaml

for some reason, I forgot to add the English numbers.

Added numbers for the English system

---

_data/language_modeling.yaml
language_modeling.md

@sebastianruder  I think we could include this dataset and papers as they have excellent perplexity of 29.2 !

New result: best LM model on wikitext 103

---

sentiment_analysis.md

The subjectivity analysis task is added, as well as the subjectivity dataset.

Added subjectivity analysis

---

sentiment_analysis.md

Source: [Learned in Translation: Contextualized Word Vectors](https://arxiv.org/abs/1708.00107)

Adding more information of the exact SST dataset

---

text_classification.md

Source: https://arxiv.org/pdf/1803.11175.pdf

Correcting size of TREC-6 dataset and name of model

---

english/sentiment_analysis.md

Added 3 new papers for SUBJ dataset

Update SUBJ SOTA

---

english/question_answering.md

I have added the dataset, emulating the style of others on the page.
The task isnt really Machine compehension, hence I have stuck it outside, next to ARC

Added ShARC task to QA

---

english/question_answering.md

was a little hasty, a few corrections to sharc description

update to Sharc desc

---

english/chunking.md

There is also an **incomplete** official implementation [here](https://github.com/hassyGo/pytorch-playground/tree/master/jmt) and they have released their embeddings [here](https://github.com/hassyGo/charNgram2vec)

add JMT to chunking.md

---

english/relationship_extraction.md

I change the estimated number from plots using WebplotDigitizer to the exact number of the results in my paper "Neural Relation Extraction with Selective Attention over Instances".

Update the results of NYT10 corpus.

---

english/word_sense_disambiguation.md

Hi, 
first of all, a big thank you for compiling and maintaining this wonderful resource!
I've added a column for 'All' in the kb-based table of the english/wsd dataset, which is formed by the concatenation of all datasets. The column is extracted from [10] and [12].

Add a column for 'All' in knowledge based WSD systems' table.

---

english/summarization.md

The Webis-TLDR-17 Corpus mined from Reddit is the first large-scale summarization corpus from the social media domain. This is an interesting addition to the various News datasets since it represents a different kind of writing on the Web.

add new summarization dataset - webis-tldr-17

---

english/relation_prediction.md

Add results of TransH, TransR, TransD on FB15K-237. The results are from OpenKE.

Update relation prediction: add results of TransH, TransR, TransD

---

english/question_answering.md

Added official github repo link for paper.

Update official source code link for NIPS paper

---

english/shallow_syntax.md

For https://github.com/sebastianruder/NLP-progress/issues/169

Add "Resolving the Scope and Focus of Negation" task to shallow syntax.

---

english/shallow_syntax.md

My bad, I should have check more carefully...

Shallow syntax: Close parenthesis.

---

english/ccg_supertagging.md
english/dependency_parsing.md
english/named_entity_recognition.md

I'd like to add results from my EMNLP 2018 paper [Semi-Supervised Sequence Modeling with Cross-View Training](https://arxiv.org/abs/1809.08370).

Add results for Cross-View Training

---

english/dialogue.md

Hi Sebastian,
Thanks for your fantastic work in maintaining this list. I'd like to add a recent result published at ACL 2018 for dialogue state tracking, as well as Nikola's WoZ dialogue state tracking dataset which is much less noisier than DSTC2.

Adding results from Global-locally Self-attentive Dialogue State Tracker

---

english/sentiment_analysis.md

The original website is down and is not on webarchive

Add mirror for sentihood + metrics in table

---

english/entity_linking.md

Link found in paper: http://aclweb.org/anthology/P18-1148

Add source code link to `Improving Entity Linking...`

---

english/sentiment_analysis.md

add SemEval-2014 Task 4 dataset and 7 new papers for aspect-based sentiment analysis

Add dataset and papers for sentiment analysis

---

english/constituency_parsing.md

this paper is from 2009 and combine several models (classic methods like PCFGs)

adding a new result to constituency parsing

---

english/dialogue.md

The progress of retrieval-based chatbot.

Add a task of dialog

---

english/language_modeling.md

I found the paper of Mikolov et al., (2011) to be more descriptive regarding the PTB dataset used than Mikolov et al., (2010), which doesn't talk at all about the dataset.

Uses a more descriptive paper for PTB

---

english/dependency_parsing.md

this is mostly because it's easier to have this here then go search for it inside some books, i had some problem to find and understand them.

defining the meaning of UAS LAS

---

chinese/chinese_word_segmentation.md

Adding more Chinese Word Segmentation Results, as well as adding missing code in the previous version.

Add more Chinese Word Segmentation Results

---

english/grammatical_error_correction.md

Fix broken formatting for JFLEG.

---

english/relationship_extraction.md

Add TACRED dataset and two papers that mainly working on it.

Add new dataset for relation extraction

---

english/language_modeling.md

Fixes a tiny typo in the first author's name.

Typo in reference for LM paper

---

english/machine_translation.md

Updated the machine translation results with numbers from [Pay Less Attention with Lightweight and Dynamic Convolutions](https://openreview.net/forum?id=SkVhlh09tX)

updated MT results with Pay Less Attention

---

english/grammatical_error_correction.md

Paper was accepted by NAACL 2019.

Add a new result for GEC

---

english/sentiment_analysis.md

Add a new sentiment analysis task on "Sentiment classification with user and product information"

Add new sentiment analysis task

---

chinese/chinese_word_segmentation.md

update recent chinese word segment results

update recent chinese word segment results

---

english/sentiment_analysis.md

Add new state-of-the-art results (accepted by NAACL 2019) for Sentihood dataset

update new Sentihood results (english/sentiment_analysis.md)

---

english/question_answering.md

1. add RACE leaderboard;
2. add SCT data source;
3. some mistakes in SCT.

 add some details to english/question_answering.md

---

english/question_answering.md

Adding the results of the 9th Question Answering over Linked Data (QALD) challenge. There are more datasets/challenge to be added in the future.

Adding Knowledge Base Question Answering Task

---

english/language_modeling.md

I know that it's only on arxiv, but it's a standard method and I think it's safe to assume that it works. here is the [link](https://arxiv.org/abs/1904.08378)

add Dynamic evaluation of Transformer to LM

---

english/sentiment_analysis.md

I made a new PR that updates both subtask 1 and 2. Please ignore the previous one.

Update sentiment_analysis.md with SemEval

---

english/named_entity_recognition.md

Fixed WNUT2017 SOTA

---

english/summarization.md

Hi, this is an amazing repo. Just noticed the link to our paper is incorrect (it links to a different paper) and also we released the official code, which I added into the readme. Thanks for checking it up

update the correct link and code for BanditSum

---

english/dialogue.md

Add task description, state-of-the-art code/paper.

Add personalized dialogue generation

---

english/dialogue.md

Add MultiWOZ DST results

---

english/summarization.md

The score put here is on their own test set.
For sasha's 1951 test set. They got:
32.67 15.59 30.64
which is mentioned in their paper (Table 1).
https://www.aclweb.org/anthology/K16-1028

correct the scores on the public dataset.

---

english/dependency_parsing.md

See [#286](https://github.com/sebastianruder/NLP-progress/issues/286).

Update Hyperlink for paper (#286)

---

chinese/chinese_word_segmentation.md

Fix a typographical error

---

english/summarization.md

Added a new record in the table with EditNet results - hybrid extractive - abstractive summarization heuristic. 
Thanks `NLP-progress` for your great work !

Update summarization results (EditNet)

---

english/sentiment_analysis.md

Added two more papers that improve on the SST-5 sentiment classification accuracy.

Update SST-5 (fine-grained sentiment) SoTA

---

english/part-of-speech_tagging.md

Results described in Ph.D. thesis but summarized in blog post.

Update PoS tagging for Twitter

---

english/sentiment_analysis.md

add within task pre-training results of BERT_base and BERT_large

add sentiment analysis results

---

english/grammatical_error_correction.md

Grammatical Error Correction: BEA-2019 Shared Task: Add metrics of top scores in Restricted and Low-resource tracks on WI-LOCNESS test-set.

Add metrics for Restricted and low-resource tracks

---

english/sentiment_analysis.md

We published a new paper about domain-related fine-tuning experiments and obtained better scores.

Update SemEval-2014 Task 4, Subtask 2 with new scores

---

english/sentiment_analysis.md

Added new result to sentiment classification with user/product info (from upcoming EMNLP paper)

Added new result to sentiment classification

---

english/relationship_extraction.md

Add new task w.r.t #341 
Please let me know if there is anything required for the merge. Thanks.

Add new task: Capturing discriminative attributes (SemEval 2018 Task 10)

---

english/summarization.md

adding Reinforced-Topic-ConvS2S model to gigaword, DUC 2004 datasets

summarization.md updtae

---

english/summarization.md

model ranking re-ordering for Gigaword

summarization.md edit

---

english/summarization.md

update CNN/DM summarization leaderboard

---

README.md

Readme file updated with Spanish Entity Linking

---

README.md
portuguese/question_answering.md

This pull request adds the Portuguese language and the Question Answering task.
The Portuguese QA task consists of the Chave collection and the results from the literature.

add Portuguese and Question Answering

---

english/word_sense_disambiguation.md

Added the WSI task, two popular WSI datasets, and the most recent papers.

Added new task: Word Sense Induction

---

english/summarization.md

@NirantK I deleted the results from the anonymized table and added to the non-anonymized table with a note.

Added note

---

README.md
nepali/nepali.md

Added a section for the Nepali language.

add nepali

---

vietnamese/vietnamese.md

Update new results on 4 Vietnamese NLP tasks: dependency parsing, machine translation, POS tagging and word segmentation.

Update new results on 4 Vietnamese NLP tasks

---

english/language_modeling.md

[Compressive Transformers for Long-Range Sequence Modelling](https://arxiv.org/abs/1911.05507)

add Compressive Transformer results

---

english/language_modeling.md

Ooops, I misspelled the reference of the paper

Fixes a typo

---

english/constituency_parsing.md

Correction of Typo on F1 score in Constituency Parsing

---

english/summarization.md

X-Sum dataset added : a pretty important dataset for abstractive summarization.
Main models added for the dataset as well.

Added X-Sum dataset + main results (Summarization)

---

english/summarization.md

@NirantK I have removed the results. Sorry for the delay, Idk why but my previous requests didn't go through.

Removed results

---

english/summarization.md

1. Gigaword results are not formally ranking and with some issue of the table.
Reranked the Models by their Rouge-2-f score and correct the format of the table.
2. Adding 2 newly accepted paper to the table and provide the link for papers and codes.

Add 2 papers and rerank the model by rouge 2

---

english/word_sense_disambiguation.md

Added Supervised WSD BERT score from EMNLP19

---

english/language_modeling.md

add results from ICML19 paper:
Improving Neural Language Modeling via Adversarial Training
http://proceedings.mlr.press/v97/wang19f/wang19f.pdf
with official code repo:
https://github.com/ChengyueGongR/advsoft

add language modeling results

---

english/machine_translation.md

add results from ICML paper:
Improving Neural Language Modeling via Adversarial Training
http://proceedings.mlr.press/v97/wang19f/wang19f.pdf

add machine translation results

---

english/coreference_resolution.md

Updated coreference resolution SoTA with 3 recently published works:
- Fei et al. (2019): End-to-end Deep Reinforcement Learning Based Coreference Resolution
- Kantor and Globerson (2019): Coreference Resolution with Entity Equalization
- Joshi et al. (2019): BERT for Coreference Resolution: Baselines and Analysis
Set a footnote for the most recent work to follow previous repo. organization, as it was getting difficult to read the train of improvements (Lee et al (2017) + BERT + ...)

Updated Coreference Resolution SoTA

---

english/machine_translation.md

Update results for MUSE(parallel multi-scale attention)

Update results for MUSE in NMT

---

english/summarization.md

https://arxiv.org/pdf/2001.04063.pdf

Add ProphetNet in Summarization

---

english/coreference_resolution.md

@sebastianruder Adding this as per the discussion on: https://github.com/sebastianruder/NLP-progress/pull/400

Add table for results on GAP dataset

---

english/dialogue.md

This adds new results for next utterance classification and conversation disentanglement.

Adding results from the Dialogue System Technology Challenge 8

---

hindi/hindi.md

added current best results as reported in:
**Neural Machine Translation for English to Hindi** (English->Hindi translation)
[https://www.researchgate.net/publication/327717152_Neural_Machine_Translation_for_English_to_Hindi ](url)
**LTRC-MT Simple & Effective Hindi-English Neural Machine Translation Systems at WAT 2019** (Hindi->English translation)
[https://www.aclweb.org/anthology/D19-5216.pdf](url)

Update Hindi-English Machine Translation

---

english/summarization.md

Add SemSim Model to Summarization

---

english/language_modeling.md

To be honest, I'm a bit skeptical about their results and asked them some questions via email. So let's put a hold on this pull request for now (unless the maintainers think it's fine) and I will update it when they answered my questions.

add TCAN results to LM

---

english/coreference_resolution.md

Add 'SpanBERT' model for Coreference Resolution

Add 'SpanBERT' for Coreference Resolution

---

english/summarization.md

These models were the successful participants of the [TL;DR challenge at INLG 2019](https://www.aclweb.org/anthology/W19-8666/)

added models for Webis-TLDR17 Corpus

---

english/summarization.md

Hi , I'm one author of ProphetNet, 
1.  The results of ProphetNet are wrong. We pretrained our model on small and large corpus, and the results on latter corpus should be reported.
2. We add our official public code link.
Thank you!

add ProphetNet code link

---

english/named_entity_recognition.md
english/word_sense_disambiguation.md

I have added Lexical Sample task to English WSD.

Adding Lexical Sample task to English WSD

---

english/summarization.md

I added another column for a quality evaluation score that we had in the paper. I forgot to do this the first time. I understand that other follow up studies may or may not do this quality evaluation, but I feel it is necessary to mention that it can be done. Also, updated the dataset link. 
Thanks again for organizing all of this!

quality evaluation score for snippet generation

---

README.md
bengali/part_of_speech_tagging.md

Hi,
I am Sagor Sarker. 
I added bengali language section. 
If you think it eligible for merge, please merge.
Hope, proper searching, I will add more results on bengali nlp research.
thanks and regards
Sagor

added bengali language section

---

english/summarization.md

Hi,
Thank you very much for maintaining this wonderful repository!
We are the authors of SemSim manuscript. We would like to exclude our work from NLP Progress - Summarization at the moment.
Please kindly understand that since our work is still in the stage of the preprint, we are gradually revising and validating the paper.
Thank you

Update for Summarization task

---

english/multimodal.md

Related to #437. Adding some VQA tasks (VQAv2, GQA, TextVQA, VizWiz) and other multimodal resources.

Vision and Language tasks

---

vietnamese/vietnamese.md

Add new SOTA results from PhoBERT for the Vietnamese  POS tagging, Dependency parsing  and NER tasks.

Add new SOTA results from PhoBERT

---

english/grammatical_error_correction.md

for An Empirical Study of Incorporating Pseudodata into Grammatical Error Correction

Adding link to official code

---

english/relationship_extraction.md

I add an update to FewRel 2 dataset in Relation Extraction challenge

Add FewRel 2 dataset

---

english/semantic_parsing.md

1. update the sota amr parsing results.
2. add the amr parsing results from [(Cai and Lam, 2019)](https://www.aclweb.org/anthology/D19-1393.pdf)
3. delete some extra whitespaces

update amr parsing results

---

english/summarization.md

Extractive summarization DiscoBERT model score update

Ext sum DiscoBERT

---

english/summarization.md

summarization PEGASUS model github add

summarization PEGASUS model github add

---

english/entity_linking.md

Results were evaluated on the GERBIL Platform and code is readily available.

Added REL results to E2E Entity Linking results.

---

english/machine_translation.md

update NMT results

---

english/part-of-speech_tagging.md

Added the official implementation (by paper author https://github.com/bohnetbd) of **Morphosyntactic Tagging with a Meta-BiLSTM Model over Context Sensitive Token Encodings** .

Add official code for Meta BiLSTM (POS)

---

english/question_answering.md

Add Natural Questions dataset to question_answering.md

Add Natural Questions

---

english/named_entity_recognition.md

This pull request adds new state-of-the-art result on CoNLL-2003 NER dataset

Added new result for CoNLL-2003 NER

---

english/relationship_extraction.md

This PR adds a new SOTA result on the TACRED relationship extraction dataset.

Added new result for TACRED dataset

---

english/question_answering.md

add logical reasoning dataset ReClor (ICLR 2020)

add logical reasoning dataset ReClor

---

english/summarization.md

The preprint is titled "GSum: A General Framework for Guided Neural Abstractive Summarization" (https://arxiv.org/pdf/2010.08014.pdf).

add a new summarization result

---

english/dialogue.md

Add link to Dialogue implementations of CASA and SGNN papers

Add dialogue implementations

---

english/common_sense.md

This PR adds a new SOTA result on the ReCoRD dataset.

Added new result for ReCoRD dataset

---

README.md
english/summarization.md
french/summarization.md
german/summarization.md
russian/summarization.md
spanish/summarization.md
turkish/summarization.md

Adding MLSUM dataset for French / German / Spanish / Russian / Turkish.

Adding MLSUM dataset

---

english/relationship_extraction.md

Hi, 
Please consider the pull request for the updated SOTA table for NYT freebase. 
Also, I have added a dataset which has been missed from the repo for relation extraction.
Abhishek

Updated SOTA NYT freebase and new dataset with SOTA for RE

---

english/sentiment_analysis.md

Adding new results for the Sentihood dataset for TABSA tasks. The paper is published in AAAI21.

Adding new results for Sentihood dataset

---

vietnamese/vietnamese.md

vELECTRA with 94.07% F1 score.

Add new Vietnamese NER result

---

vietnamese/vietnamese.md

UITws-v1 with 98.06 on F1 score.

Add SOTA result for Vietnamese Word segmentation

---

english/named_entity_recognition.md

Added new Named Entity Recognition (NER) results in User-generated text (WNUT 2017) and (CoNLL 2003)

PR: Added new NER results in the section WNUT 2017 and CoNLL 03 with the paper official link (updated)

---

english/coreference_resolution.md

Include results from our recent paper (to appear at ACL)

Include coreference results from our recent paper (to appear at ACL)

---

spanish/named_entity_recognition.md

I added a new task for Spanish NER. It is for social media data. The task is presented at NAACL 2021

Added ProfNER (social media) shared task to Spanish NER

---

english/question_answering.md

Also fixed link for SWAG leaderboard

Added AdversarialQA

---

english/semantic_parsing.md

Hi,
I added the new SOTA results from our AAAI 2021 paper:
https://ojs.aaai.org/index.php/AAAI/article/view/17489

New SOTA added

---

english/grammatical_error_correction.md

[Improving Sequence Tagging for Grammatical Error Correction ](https://er.ucu.edu.ua/handle/1/2707)

Add GECToR large results for Grammatical Error Correction

---

english/simplification.md

Text Simplification by Tagging (https://aclanthology.org/2021.bea-1.2.pdf)

Add TST Results for Text Simplification

---

english/summarization.md

Added SimCLS model for CNN/DailyMail dataset. This work is published at ACL 2021 as a short paper.

Added new result for summarization

---

english/taxonomy_learning.md

I would like to add a subsection about the Taxonomy Enrichment task and several datasets for different task settings for the English language

Add subsection about the Taxonomy Enrichment task

---

english/semantic_parsing.md

Latest results from a published paper for AMR parsing

Adding new results for AMR parsing

---

README.md
russian/sentiment-analysis.md

I would like to provide RuSentRel dataset details into the Russian section of this repository. This dataset become a research basis of the particular sentiment analysis task, dubbed as "Sentiment Attitude Extraction".

Add results for Sentiment Analysis in Russian (Sentiment Attitude Extraction Task)

---

english/ccg.md

Add a paper from Tian et al. (2020) published in EMNLP-2020 for CCG supertagging.

Add a paper to supertagging on CCGBank

---

english/named_entity_recognition.md

Add a paper from Nie et al. (2020) published at EMNLP-2020: findings.

Add a paper on Ontonotes v5 (English)

---

bengali/sentiment_analysis.md

Added details description of SentNoB

sentiment analysis for Bangla added

---

README.md

This change is for the users to find bengali/sentiment_analysis.md from the readme.md

Mapped the progress .md on the readme.md

---

english/word_sense_disambiguation.md

Add new results for EMNLP 2021 Findings Paper [Improved Word Sense Disambiguation with Enhanced Sense Representations](https://aclanthology.org/2021.findings-emnlp.365.pdf).

Add new results for word sense disambiguation

---

english/sentiment_analysis.md

Add new results of "Sentiment classification with user and product information"

Add new results of "SA with user and product information"

---

README.md
german/question_answering.md

Adding a German-language question answering dataset in the language-specific part of the repo.

add german question answering dataset

---

english/word_sense_disambiguation.md

English Word Sense Disambiguation results added.
Reference paper: https://aclanthology.org/2021.emnlp-main.112.pdf
Code: https://github.com/SapienzaNLP/consec

added ConSeC result to word sense disambiguation

---

english/taxonomy_learning.md

add results on the diachronic datasets for the paper "Taxonomy enrichment with text and graph vector representations" (Published: 6 April 2022)

Add new results to Taxonomy_learning.md

---

english/machine_translation.md
english/paraphrase-generation.md

| Model           | BLEU  |  Paper / Source |
| ------------- | :-----:| --- |
| vanilla MNMT models| 17.95 | [Tencent’s Multilingual Machine Translation System for WMT22 Large-Scale African Languages](https://arxiv.org/pdf/2210.09644v1.pdf)|

add this to machine translation,. Is it okay?
